export const UPDATE_SINGER_LIST = 'singers/UPDATE_SINGER_LIST';
export const UPDATE_PAGE_INDEX = 'singers/UPDATE_PAGE_INDEX';
export const UPDATE_ENTER_LOADING = 'singers/UPDATE_ENTER_LOADING';
export const UPDATE_PULL_DOWN_LOADING = 'singers/UPDATE_PULL_DOWN_LOADING';
export const UPDATE_PULL_UP_LOADING = 'singers/UPDATE_PULL_UP_LOADING';
